### PR TITLE
Added async support

### LINKED ISSUE #2: Async compatibility issues
When trying to use this library on embedded Tomcat with Async enabled, I get the following error

```
Async support must be enabled on a servlet and for all filters involved in async request processing.
```

Could you add async support here?

### PR DESCRIPTION
**Pull request by fiunchinho**
Fixes #2

### CODE REVIEW

**Comment by akihyro** [comment]
Thanks for pull request.

**Comment by fiunchinho** [comment]
Could you release a new version with the new code? Thank you!

**Comment by akihyro** [comment]
v1.1 has been released!

http://search.maven.org/#artifactdetails%7Cnet.rakugakibox.springbootext%7Cspring-boot-ext-logback-access%7C1.1%7C

**Comment by fiunchinho** [comment]
Awesome!

Image of Yaktocat

**Pull request merged**
